import type { Metadata } from "next";
import { Poppins, Montserrat } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import { Providers } from "@/components/providers";
import Footer from "@/components/footer";
import BackgroundOrbs from "@/components/layout/background-orbs";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Quirklr",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {" "}
      <body
        className={`${poppins.variable} ${montserrat.variable} overflow-x-hidden antialiased`}
      >
        <Providers>
          <Header />
          <BackgroundOrbs />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
